apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: petehakkarainen/hello-world:1.0.2
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: CONTAINER_COLOR
              value: teal
            - name: TITLE
              value: Container Information              
            - name: PETS
              value: whitecows   
          readinessProbe:
            httpGet:
              port: web
              path: /
